### ISSUE TITLE
Missing composer package

### ISSUE THREAD

**Issue by wodCZ** [heureka/inflection#6]
At first, thank you for this package!

At time of writing this issue, `heureka/inflection` couldn't be found on packagist.

As a temporary workaround, I've put this:
```
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/heureka/inflection"
		}
	]
```
in our composer.json.

**UPDATE: also, new release would be great, because currently tagged v2.0 contains unnecessary var_dump (which have been fixed, but not released).**

**Comment by jannavratil** [comment]
Thanks for comments. Package was added to packagist and new release was released ;)
