### ISSUE TITLE
Přítel, 5. pád

### ISSUE THREAD

**Issue by mstrouhal** [heureka/inflection#8]
Ahoj, díky za super knihovnu! :+1: 

Přišel jsem na malou chybku. u slova "Přítel" a podobných knihovna generuje v pátém pádě "Přítel" místo "Příteli"

**Comment by jannavratil** [comment]
Ahoj, díky za podnět. 
Ideální stav by bylo, kdybys připravil opravný PR. V opačném případě to zkusím zařadit do našich procesů vývoje.
